version: "2"
services:

  db:
    build:
      context: ./
      dockerfile: docker/dev/db.Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_db
    container_name: ${COMPOSE_PROJECT_NAME}_db_1
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: docker
      POSTGRES_PASSWORD: secret
    ports:
      - "54322:5432"

  web:
    build:
      context: ./
      dockerfile: docker/dev/web.Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_web
    container_name: ${COMPOSE_PROJECT_NAME}_web_1
    ports:
      - "8089:80"
    volumes_from:
    - app

  node:
    build:
      context: ./
      dockerfile: docker/dev/node.Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_node
    container_name: ${COMPOSE_PROJECT_NAME}_node_1
    tty: true
    volumes:
      - ./:/var/www

  app:
    build:
      context: ./
      dockerfile: docker/dev/app.Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_app
    container_name: ${COMPOSE_PROJECT_NAME}_app_1
    volumes:
    - ./:/var/www
    #- ~/.ssh:/home/docker-user/.ssh -- pass your local ssh key
    depends_on:
      - db
